### PR TITLE
Ported to ATtiny85

### PR DESCRIPTION
**Pull request by sanchosk**
For usage, please, read the comments within the file

### CODE REVIEW

**Comment by misan** [comment]
Brilliant, thanks for sharing it.

**Comment by sanchosk** [comment]
No problem - I would not be able to even start without your initial code - that's where the credit is due :)
Now I can get 2 ATtiny chips, one L298 and start to design the mechanical part...

**Comment by roboprint** [comment]
HVSP should be used in any case after uploading non-debug version into attiny? Or it is possible to detect external debug request in non-debug firmware for example by connecting encA and encB together and detecting this case at setup() function?

**Comment by sanchosk** [comment]
Good idea, haven't thought about that. I think I would rather move to motor pins for the debug start - therefore HVSP would not be needed until a serious change in code is required.
However, the problem here is that SoftwareSerial for Tiny uses interrupts - the same as I am using for the encoder. Therefore it is quite difficult for me to implement both Encoder and SW serial.
Will have to investigate a bit...

However, HVSP in this case equals to 6x 1kOhm resistors and 1 NPN transistor, so not that big deal.

**Comment by michaeljball** [comment]
Great work on this.  I had started my work on an ATTiny (84, not 85) a while ago but couldn't get past the software serial interrupt limitations.   

Cheers.

**Pull request merged**
